spring.datasource.url=jdbc:postgresql://localhost:5432/student_productivity
spring.datasource.username=postgres
spring.datasource.password=12344321

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true